spring.main.web-application-type=reactive

server.port=8082
spring.application.name=api-gateway

# JWT Configuration
# This secret key must be a Base64 encoded string.
jwt.secret=S3VwY0R2Y0t5cEpTUDd1c0F4bVd5Q3JpS1NlOW16c2FNd2V5Q3JpS1NlOW16c2FNc3Y=
jwt.expiration=86400000

spring.cloud.gateway.routes[0].id=authenticate_route
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/authenticate


## Route for the authentication service
#spring.cloud.gateway.server.webflux.routes[0].id=auth_service_route
#spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/authenticate/**
#
## Route for the public products service endpoint
#spring.cloud.gateway.server.webflux.routes[1].id=products_public_route
#spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8083
#spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/products/public
## Pass isPublic=true to the filter to skip authentication
#spring.cloud.gateway.server.webflux.routes[1].filters[0]=JwtAuthentication=isPublic:true
#
## Route for the secured products service endpoint
#spring.cloud.gateway.server.webflux.routes[2].id=products_secured_route
#spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
#spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/products/secured
## Pass isPublic=false to the filter to enforce authentication
#spring.cloud.gateway.server.webflux.routes[2].filters[0]=JwtAuthentication=isPublic:false