spring.main.web-application-type=reactive

server.port=8082
spring.application.name=api-gateway

jwt.secret=S3VwY0R2Y0t5cEpTUDd1c0F4bVd5Q3JpS1NlOW16c2FNd2V5Q3JpS1NlOW16c2FNc3Y=
jwt.expiration=86400000

spring.cloud.gateway.routes[0].id=authenticate_route
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/authenticate

