spring.application.name=secure-gateway-backend-service
jwt.secret=S3VwY0R2Y0t5cEpTUDd1c0F4bVd5Q3JpS1NlOW16c2FNd2V5Q3JpS1NlOW16c2FNc3Y=
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
